### ISSUE TITLE
Issue running in windows 11 - java.lang.NoClassDefFoundError: javax/xml/bind/JAXBContext

### ISSUE THREAD

**Issue by deostroll** [danielricci/solitaire#183]
I get the following error when trying to run on windows 11.

<img width="960" alt="image" src="https://github.com/danielricci/solitaire/assets/415336/978e98ed-1f90-4c4b-9f21-b625cd4d3efd">

How to resolve?

Ps: I have openjdk installed on my machine.

**Comment by danielricci** [comment]
Install Java 1.8On May 16, 2024, at 15:30, arun.jayapal ***@***.***> wrote:﻿
I get the following error when trying to run on windows 11.
image.png (view on web)
How to resolve?
Ps: I have openjdk installed on my machine.
